title:             보스백 블로그
email:             bgc8214@gmail.com  
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
